[build]
target = "mips-nintendo64-none"

[target.mips-nintendo64-none]
runner = ["cargo-n64", "run", "--ipl3", "6102"]
rustflags = [
    "-C", "link-arg=-Tn64.ld",
    "-C", "target-feature=+float,+soft-float",
]

[unstable]
build-std = ["core", "alloc"]