name: n64soul-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tooling (Rust)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: mips-nintendo64-none

      - name: Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y lld

      - name: Generate debug weights (ephemeral)
        run: |
          python tools/make_debug_weights.py \
            --out-bin n64llm/n64-rust/assets/weights.bin \
            --out-man n64llm/n64-rust/assets/weights.manifest.bin
          python tools/validate_weights.py \
            --bin n64llm/n64-rust/assets/weights.bin \
            --man n64llm/n64-rust/assets/weights.manifest.bin --crc

      - name: Host unit tests (asset-free)
        run: cargo test --lib --verbose
        working-directory: n64llm/n64-rust

      - name: Build N64 ROM
        run: |
          cargo install cargo-n64
          cd n64llm/n64-rust
          cargo n64 build --release
          echo "### ROM output" >> $GITHUB_STEP_SUMMARY
          find target -type f -name "*.z64" -printf "* %p (%k KiB)\n" >> $GITHUB_STEP_SUMMARY

      - name: Scrub ephemerals
        run: |
          rm -f n64llm/n64-rust/assets/weights.bin n64llm/n64-rust/assets/weights.manifest.bin
          find n64llm/n64-rust/target -type f \( -name "*.z64" -o -name "*.n64" \) -delete
