name: n64soul-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tooling (Rust - nightly for N64)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y lld

      - name: Host unit tests (asset-free)
        run: |
          cargo test --lib --verbose --features host
          cargo test --test host_sanity --verbose --features host
        working-directory: n64llm/n64-rust

      - name: Generate debug weights (ephemeral)
        run: |
          python tools/make_debug_weights.py \
            --out-bin n64llm/n64-rust/assets/weights.bin \
            --out-man n64llm/n64-rust/assets/weights.manifest.bin
          python tools/validate_weights.py \
            --bin n64llm/n64-rust/assets/weights.bin \
            --man n64llm/n64-rust/assets/weights.manifest.bin --crc

      - name: Build N64 ROM (release)
        working-directory: n64llm/n64-rust
        run: |
          rustup toolchain install nightly --profile minimal
          cargo +nightly install cargo-n64
          cargo +nightly -Z build-std=core,alloc n64 build --release

      - name: Scrub ephemerals
        run: |
          rm -f n64llm/n64-rust/assets/weights.bin n64llm/n64-rust/assets/weights.manifest.bin
          find n64llm/n64-rust/target -type f \( -name "*.z64" -o -name "*.n64" \) -delete

      - name: No binaries leaked into tree
        run: |
          set -e
          test ! -e n64llm/n64-rust/assets/weights.bin
          test ! -e n64llm/n64-rust/assets/weights.manifest.bin
          ! git ls-files -o --exclude-standard | grep -E '\.(bin|z64|n64)$' || (echo "Found stray binaries"; exit 1)
